### ISSUE TITLE
Windows compiling problems

### ISSUE THREAD

**Issue by sonovice** [rism-ch/verovio#296]
Sorry for always coming up with this, but ~~verovio is a real diva when it comes to Windows~~ Windows is a real diva when it comes to verovio.
After I have already given up to use the python wrapper, I now wanted to simply compile the CLI tool with Visual Studio 2015.

Here is what I did:

```
cd tools
cmake . -DNO_PAE_SUPPORT=ON -DNO_HUMDRUM_SUPPORT=ON
```

Then I opened the generated solution `Verovio.sln` in VS 2015, selected "Release Win32" and hit "Build".
The compiler now seems to be caught in an endless loop, it just never finishes and the log messages repeat themselves.
Among the first few lines, this error comes up:
```
\tools\main.cpp(9): fatal error C1083: Cannot open include file: 'getopt.h': No such file or directory
```

Is there any way to improve the general Windows compatibility of this project? Maybe automated tests in a VM? I would be really glad to help, but I don't know where to start.

**Comment by craigsapp** [comment]
Windows?  What is that?

```
\tools\main.cpp(9): fatal error C1083: Cannot open include file: 'getopt.h': No such file or directory
```

Looking on the web, I see this article:

https://www.codefull.org/2015/04/cannot-find-getopt-h-header-file-when-compiling-under-windows

So including that code in VS 2015 should fix that particular problem.  Getopt is a unixism, so that seems to be why it is misisng in VS 2015.  Getopt is used to parse command-line arguments in unix, and as Windows does not really have a command-line (other than the new ubuntu interface which I have not tried yet), it does not need getopt.

https://en.wikipedia.org/wiki/Getopt

One possibility, @lpugin, is to use the humlib Options class, which is what I use instead getopt.

https://github.com/craigsapp/humlib/blob/master/include/Options.h
https://github.com/craigsapp/humlib/blob/master/src/Options.cpp

example usage:

```cpp
int main(int argc, char** argv) {
    Options opts;
    opts.define("b|border=i:20", "Add border");
    opts.define("f|format=s:auto", "Select input format");
    opts.define("h|page-height=i:2970", "Page height");
    opts.define("o|outfile:s", "Output file name base");
    opts.define("r|resources:s", "Resources path");
    opts.define("s|scale=d:100", "Scale percent");
    opts.define("t|type=s:svg", "Output type");
    opts.define("v|version=b", "Display version number");
    opts.define("w|page-width=i:1025", "Page width");
    opts.define("adjust-page-height=b", "Autocrop page height");
    opts.define("all-pages=b", "Output all pages");
    opts.process(argc, argv);

    int border = opts.getInteger("border");
    double scale = opts.getDouble("scale");
    string outfilebase = opts.getString("outfile");
    bool allpages = opts.getBoolean("allpages");
```

**Comment by lpugin** [comment]
> Sorry for always coming up with this

No problem at all

> but verovio is a real diva when it comes to Windows.

For the records, it compiles without any waring under Linux, FreeBSD, MacOS with both cmake and XCode. So sorry, but if there is a diva in this game it is Windows and not Verovio. BTW, Windows is the only platform for which we had to introduce specific ```#define```...

> \tools\main.cpp(9): fatal error C1083: Cannot open include file: 'getopt.h': No such file or directory

I assume that either WIN32 is not defined of the ./include/win32/ path is not given. I am looking at it but for now it is downloading 10GB of MS developer tools.

> Is there any way to improve the general Windows compatibility of this project? Maybe automated tests in a VM? I would be really glad to help, but I don't know where to start.

Not sure where to start either. Maybe they are ideas around here? Thanks for your offer to help.

**Comment by xhero** [comment]
That is because **getopt** is not available on win32. You can either copy it and add it to the sources, or use a replacement.

**Comment by lpugin** [comment]
Thanks. We should probably just include it in our ../win32/win32.h file

**Comment by sonovice** [comment]
> if there is a diva in this game it is Windows and not Verovio. BTW, Windows is the only platform for which we had to introduce specific #define...

Sorry, I didn't mean to be blunt here. Handling POSIX and Windows at the same time is always like juggling with porcelain...

> Not sure where to start either. Maybe they are ideas around here?

Maybe instead of using a full-featured CI system (of which I only know the non-free Docker Cloud to be able to handle Windows), a quick "watch for git changes -> checkout git, compile with VS, and mail the error log" script might work in a Windows VM. This is obviously nowhere near real automated build testing, but it's a starting point to at least get the major build problems every now and then.

**Comment by lpugin** [comment]
No problem. Could you try to concatenate the getopt.h file to the win32.h file we have?

**Comment by sonovice** [comment]
Did that. The error is gone but compiling still results in a loop.

**Comment by lpugin** [comment]
Too bad. More precisely, what do you mean by a loop?

**Comment by ahankinson** [comment]
AppVeyor (https://www.appveyor.com) seems to support Windows builds and is free for OSS, if that's useful.

**Comment by craigsapp** [comment]
I haven't used Visual Studio in a long time (since version 6), instead when I want to compile natively for Windows computers, I cross-compile in linux/unix with MinGW:

      https://en.wikipedia.org/wiki/MinGW

> MinGW can be run either on the native Microsoft Windows platform, cross-hosted on Linux (or other Unix), or "cross-native" on Cygwin.

**Comment by lpugin** [comment]
MinGW sounds like a reasonable option to me. So does AppVeyor if somebody wants to set it up, but this might be over the top

**Comment by lpugin** [comment]
Actually MinGW looks not very active anymore...

**Comment by sonovice** [comment]
> Too bad. More precisely, what do you mean by a loop?

It just never stops compiling. The log messages seam to repeat themselves over and over again.

> So does AppVeyor if somebody wants to set it up, but this might be over the top

Just tried it. Very easy, got it up and running in under 2 minutes. The automated builds for my fork can be found here: [https://ci.appveyor.com/project/sonovice/verovio](https://ci.appveyor.com/project/sonovice/verovio)

**Comment by lpugin** [comment]
pretty cryptic messages....

**Comment by lpugin** [comment]
You should start by fixing the first warning and add a new line at the end of getopt.h

**Comment by sonovice** [comment]
> You should start by fixing the first warning and add a new line at the end of getopt.h

Done.

**Comment by lpugin** [comment]
Still not sure about this warning 
```
C:\projects\verovio\tools\..\include\win32/getopt.h(13): warning C4081: expected 'newline'; found ';' [C:\projects\verovio\tools\verovio.vcxproj
```
Maybe you should comment line 13?

**Comment by sonovice** [comment]
Fixed it. But that's so minor, it doesn't matter at all...

**Comment by lpugin** [comment]
Sometimes problems in the header files generate hard to track errors, so it is good to fix the first ones.

**Comment by lpugin** [comment]
Also, the warnings comes for the system headers, you might want to have a look at this
http://stackoverflow.com/questions/4001736/whats-up-with-the-thousands-of-warnings-in-standard-headers-in-msvc-wall

**Comment by sonovice** [comment]
Here we go. Now it's somewhat clearer: [![Build status](https://ci.appveyor.com/api/projects/status/x5ojbtsqaipi72cs?svg=true)](https://ci.appveyor.com/project/sonovice/verovio)

**Comment by sonovice** [comment]
Alright, I've come pretty far... Had to change a lot of things to get rid of all the errors.
No idea how to fix that last one though: [![Build status](https://ci.appveyor.com/api/projects/status/x5ojbtsqaipi72cs?svg=true)](https://ci.appveyor.com/project/sonovice/verovio)

**Comment by craigsapp** [comment]
If you define` _NO_HUMDRUM_SUPPORT_` the following warnings should disappear.   You could add the line:
```
    #define _NO_HUMDRUM_SUPPORT_ 
```
at the top of `src/iohumdrum.cpp` to force suppression of the code (but maybe that will not suppress compiling humlib.cpp, in which case you can remove it for compiling in AppVeyor or in setup.py).  I will try out AppVeyor and see how to fix or suppress the warnings:

```
C:\projects\verovio\src\hum\humlib.cpp(1837): warning C4311: 'type cast': pointer truncation from 'void *' to 'hum::TEMP64BITFIX' [C:\projects\verovio\tools\verovio.vcxproj]
C:\projects\verovio\src\hum\humlib.cpp(1837): warning C4302: 'type cast': truncation from 'void *' to 'hum::TEMP64BITFIX' [C:\projects\verovio\tools\verovio.vcxproj]
C:\projects\verovio\src\hum\humlib.cpp(1837): warning C4311: 'type cast': pointer truncation from 'hum::_HumInstrument *' to 'hum::TEMP64BITFIX' [C:\projects\verovio\tools\verovio.vcxproj]
C:\projects\verovio\src\hum\humlib.cpp(1837): warning C4302: 'type cast': truncation from 'hum::_HumInstrument *' to 'hum::TEMP64BITFIX' [C:\projects\verovio\tools\verovio.vcxproj]
C:\projects\verovio\src\hum\humlib.cpp(11355): warning C4503: 'std::_Tree<std::_Tmap_traits<_Kty,_Ty,_Pr,_Alloc,false>>::_Insert_hint': decorated name length exceeded, name was truncated [C:\projects\verovio\tools\verovio.vcxproj]
          with
          [
              _Kty=std::string,
              _Ty=std::map<std::string,std::map<std::string,hum::HumParameter,std::less<std::string>,std::allocator<std::pair<const std::string,hum::HumParameter>>>,std::less<std::string>,std::allocator<std::pair<const std::string,std::map<std::string,hum::HumParameter,std::less<std::string>,std::allocator<std::pair<const std::string,hum::HumParameter>>>>>>,
              _Pr=std::less<std::string>,
              _Alloc=std::allocator<std::pair<const std::string,std::map<std::string,std::map<std::string,hum::HumParameter,std::less<std::string>,std::allocator<std::pair<const std::string,hum::HumParameter>>>,std::less<std::string>,std::allocator<std::pair<const std::string,std::map<std::string,hum::HumParameter,std::less<std::string>,std::allocator<std::pair<const std::string,hum::HumParameter>>>>>>>>
          ]
C:\projects\verovio\src\hum\humlib.cpp(11355): warning C4503: 'std::_Tree<std::_Tmap_traits<_Kty,_Ty,_Pr,_Alloc,false>>::_Insert_at': decorated name length exceeded, name was truncated [C:\projects\verovio\tools\verovio.vcxproj]
          with
          [
              _Kty=std::string,
              _Ty=std::map<std::string,std::map<std::string,hum::HumParameter,std::less<std::string>,std::allocator<std::pair<const std::string,hum::HumParameter>>>,std::less<std::string>,std::allocator<std::pair<const std::string,std::map<std::string,hum::HumParameter,std::less<std::string>,std::allocator<std::pair<const std::string,hum::HumParameter>>>>>>,
              _Pr=std::less<std::string>,
              _Alloc=std::allocator<std::pair<const std::string,std::map<std::string,std::map<std::string,hum::HumParameter,std::less<std::string>,std::allocator<std::pair<const std::string,hum::HumParameter>>>,std::less<std::string>,std::allocator<std::pair<const std::string,std::map<std::string,hum::HumParameter,std::less<std::string>,std::allocator<std::pair<const std::string,hum::HumParameter>>>>>>>>
          ]
C:\projects\verovio\src\hum\humlib.cpp(11355): warning C4503: 'std::_Tree<std::_Tmap_traits<_Kty,_Ty,_Pr,_Alloc,false>>::_Insert_nohint': decorated name length exceeded, name was truncated [C:\projects\verovio\tools\verovio.vcxproj]
          with
          [
              _Kty=std::string,
              _Ty=std::map<std::string,std::map<std::string,hum::HumParameter,std::less<std::string>,std::allocator<std::pair<const std::string,hum::HumParameter>>>,std::less<std::string>,std::allocator<std::pair<const std::string,std::map<std::string,hum::HumParameter,std::less<std::string>,std::allocator<std::pair<const std::string,hum::HumParameter>>>>>>,
              _Pr=std::less<std::string>,
              _Alloc=std::allocator<std::pair<const std::string,std::map<std::string,std::map<std::string,hum::HumParameter,std::less<std::string>,std::allocator<std::pair<const std::string,hum::HumParameter>>>,std::less<std::string>,std::allocator<std::pair<const std::string,std::map<std::string,hum::HumParameter,std::less<std::string>,std::allocator<std::pair<const std::string,hum::HumParameter>>>>>>>>
          ]
C:\projects\verovio\src\hum\humlib.cpp(11355): warning C4503: 'std::_Tree<std::_Tmap_traits<_Kty,_Ty,_Pr,_Alloc,false>>::_Buynode_if_nil': decorated name length exceeded, name was truncated [C:\projects\verovio\tools\verovio.vcxproj]
          with
          [
              _Kty=std::string,
              _Ty=std::map<std::string,std::map<std::string,hum::HumParameter,std::less<std::string>,std::allocator<std::pair<const std::string,hum::HumParameter>>>,std::less<std::string>,std::allocator<std::pair<const std::string,std::map<std::string,hum::HumParameter,std::less<std::string>,std::allocator<std::pair<const std::string,hum::HumParameter>>>>>>,
              _Pr=std::less<std::string>,
              _Alloc=std::allocator<std::pair<const std::string,std::map<std::string,std::map<std::string,hum::HumParameter,std::less<std::string>,std::allocator<std::pair<const std::string,hum::HumParameter>>>,std::less<std::string>,std::allocator<std::pair<const std::string,std::map<std::string,hum::HumParameter,std::less<std::string>,std::allocator<std::pair<const std::string,hum::HumParameter>>>>>>>>
```

**Comment by sonovice** [comment]
Thanks @craigsapp, but Humdrum does not seem to be the root of the problems. The Linker is looking for something odd at the very end...
(BTW: Check my fork, I fixed a lot of false logical operators in your humdrum files.)

**Comment by craigsapp** [comment]
Hi @sonovice,  They are legitimate logical operators that are part of the C++ standard from about 2003, see section 2.6 page 20 in https://isocpp.org/files/papers/N3690.pdf

`and` is equivalent to `&&`, `or` is equivalent to `||` and `not` is equivalent to `!`.

https://github.com/sonovice/verovio/commit/e7d3258412f52b2616a731a59367c0060e49a458

https://github.com/sonovice/verovio/commit/e1d57b17788fdc62ff908b61c273faf0943f8777

That is from code I copied off of the internet.  I don't use those alternates myself, so changing them to the symbolic form is fine; and as I like my code to be operating system/compiler neutral as possible, I would now prefer the symbols to the alternates.  Perhaps Visual Studio turns them off by default to support legacy code...

http://stackoverflow.com/questions/24414124/why-does-vs-not-define-the-alternative-tokens-for-logical-operators

So yet again, Microsoft is the diva.

**Comment by sonovice** [comment]
Wow, I honestly didn't know that, so thank you very much for your explanation. And thanks again Microsoft for being so stubborn...

**Comment by sonovice** [comment]
Oh, just in case anyone wants to play with AppVeyor, this is my current configuration:
```
version: 1.0.{build}
image: Visual Studio 2015
configuration: Release
platform: x64
before_build:
- cmd: >-
    cd tools

    cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DNO_PAE_SUPPORT=ON .
build:
  project: tools/Verovio.sln
  verbosity: minimal
```

**Comment by craigsapp** [comment]
That is handy, as that was just what I was going to try to figure out:

```
version: 1.0.{build}
image: Visual Studio 2015
configuration: Release
platform: x64
before_build:
- cmd: >-
    cd tools

    cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DNO_PAE_SUPPORT=ON .
build:
  project: tools/Verovio.sln
  verbosity: minimal
```

**Comment by lpugin** [comment]
I tried to change the string stream to output ss, but I doubt this will fix the linker error.

**Comment by sonovice** [comment]
I've cleaned up the mess in my fork. Commits should now be commented more clearly. Couldn't figure out the linker error though...

**Comment by lpugin** [comment]
It is a very weird error. Could you try to pass a ```const string``` LoadString in main?

```
        const string data = data_stream.str();
        if (!toolkit.LoadString(data)) {
            cerr << "The input could not be loaded." << endl;
            exit(1);
        }
```

**Comment by sonovice** [comment]
Did not help unfortunately

**Comment by lpugin** [comment]
Does it link if you comment it?

**Comment by lpugin** [comment]
Possible conflict?
https://msdn.microsoft.com/en-us/library/windows/desktop/ms647486(v=vs.85).aspx

**Comment by sonovice** [comment]
Yes, this really the last problem right now.

**Comment by sonovice** [comment]
> Possible conflict?

Probably... How could I miss that? What would be the best way to fix this?

**Comment by lpugin** [comment]
Try to rename it as LoadData

I still don't understand why the linker does not find it because it is a class method...

**Comment by sonovice** [comment]
Worked! Time for a pull request. It would be nice if you could add AppVeyor to your repository so future complications can be detected immediately. Maybe we can discuss this in person next week in Detmold.

**Comment by sonovice** [comment]
#300
