### ISSUE TITLE
Disassociated stems for cross-staff notes

### ISSUE THREAD

**Issue by craigsapp** [rism-ch/verovio#546]
Here is a funny behavior which is from a recent update:

<img width="318" alt="screen shot 2017-04-15 at 10 35 33 pm" src="https://cloud.githubusercontent.com/assets/3487289/25069113/a8e230d0-222c-11e7-93da-a8abfc517046.png">

The stems are remaining on staff one, but the notes are on staff 2.

MEI test data:

```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application isodate="2017-04-15T22:35:23" version="0.9.14-dev-0d11ab2-dirty">
                    <name>Verovio</name>
                    <p>Transcoded from Humdrum</p>
                </application>
            </appInfo>
        </encodingDesc>
        <workDesc>
            <work>
                <titleStmt>
                    <title />
                </titleStmt>
            </work>
        </workDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-0000001934174128" midi.bpm="120">
                        <staffGrp xml:id="staffgrp-0000001049415961" symbol="brace" barthru="true">
                            <staffDef xml:id="staffdef-0000001019613042" n="1" clef.shape="G" clef.line="2" key.sig="0" meter.count="4" meter.unit="4" meter.sym="common" lines="5" />
                            <staffDef xml:id="staffdef-0000000001858391" n="2" clef.shape="F" clef.line="4" key.sig="0" meter.count="4" meter.unit="4" meter.sym="common" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-0000001418485209">
                        <measure xml:id="measure-L12" n="98" type="m-98">
                            <staff xml:id="staff-L12F2N1" n="1">
                                <layer xml:id="layer-L12F2N1" n="1">
                                    <chord xml:id="chord-L13F2" dur="2">
                                        <note xml:id="note-L13F2S1" staff="2" oct="3" pname="d">
                                            <accid xml:id="accid-L13F2S1" accid.ges="n" />
                                        </note>
                                        <note xml:id="note-L13F2S2" staff="2" oct="3" pname="f">
                                            <accid xml:id="accid-L13F2S2" accid.ges="n" />
                                        </note>
                                    </chord>
                                    <chord xml:id="chord-L21F2" dur="16">
                                        <note xml:id="note-L21F2S1" staff="2" oct="3" pname="c">
                                            <accid xml:id="accid-L21F2S1" accid.ges="n" />
                                        </note>
                                        <note xml:id="note-L21F2S2" staff="2" oct="3" pname="e">
                                            <accid xml:id="accid-L21F2S2" accid.ges="n" />
                                        </note>
                                    </chord>
                                    <beam xml:id="beam-L22F2-L24F2">
                                        <note xml:id="note-L22F2" dur="16" oct="4" pname="c">
                                            <accid xml:id="accid-L22F2" accid.ges="n" />
                                        </note>
                                        <note xml:id="note-L23F2" dur="16" oct="3" pname="b">
                                            <accid xml:id="accid-L23F2" accid.ges="n" />
                                        </note>
                                        <note xml:id="note-L24F2" dur="16" oct="4" pname="c">
                                            <accid xml:id="accid-L24F2" accid.ges="n" />
                                        </note>
                                    </beam>
                                    <beam xml:id="beam-L25F2-L28F2">
                                        <note xml:id="note-L25F2" dur="16" oct="3" pname="g">
                                            <accid xml:id="accid-L25F2" accid.ges="n" />
                                            <artic xml:id="artic-L25F2" artic="stacc" />
                                        </note>
                                        <note xml:id="note-L26F2" dur="16" oct="4" pname="g">
                                            <accid xml:id="accid-L26F2" accid.ges="n" />
                                        </note>
                                        <note xml:id="note-L27F2" dur="16" oct="4" pname="f">
                                            <accid xml:id="accid-L27F2" accid="s" />
                                        </note>
                                        <note xml:id="note-L28F2" dur="16" oct="4" pname="g">
                                            <accid xml:id="accid-L28F2" accid.ges="n" />
                                        </note>
                                    </beam>
                                </layer>
                            </staff>
                            <staff xml:id="staff-L12F1N1" n="2">
                                <layer xml:id="layer-L12F1N1" n="1">
                                    <beam xml:id="beam-L13F1-L16F1">
                                        <note xml:id="note-L13F1" dur="16" oct="2" pname="c" stem.dir="down">
                                            <accid xml:id="accid-L13F1" accid.ges="n" />
                                        </note>
                                        <note xml:id="note-L14F1" dur="16" oct="3" pname="c" stem.dir="down">
                                            <accid xml:id="accid-L14F1" accid.ges="n" />
                                        </note>
                                        <note xml:id="note-L15F1" dur="16" oct="2" pname="b" stem.dir="down">
                                            <accid xml:id="accid-L15F1" accid.ges="n" />
                                        </note>
                                        <note xml:id="note-L16F1" dur="16" oct="3" pname="c" stem.dir="down">
                                            <accid xml:id="accid-L16F1" accid.ges="n" />
                                        </note>
                                    </beam>
                                    <beam xml:id="beam-L17F1-L20F1">
                                        <note xml:id="note-L17F1" dur="16" oct="2" pname="b" stem.dir="down">
                                            <accid xml:id="accid-L17F1" accid.ges="n" />
                                        </note>
                                        <note xml:id="note-L18F1" dur="16" oct="3" pname="c" stem.dir="down">
                                            <accid xml:id="accid-L18F1" accid.ges="n" />
                                        </note>
                                        <note xml:id="note-L19F1" dur="16" oct="2" pname="b" stem.dir="down">
                                            <accid xml:id="accid-L19F1" accid.ges="n" />
                                        </note>
                                        <note xml:id="note-L20F1" dur="16" oct="3" pname="c" stem.dir="down">
                                            <accid xml:id="accid-L20F1" accid.ges="n" />
                                        </note>
                                    </beam>
                                    <note xml:id="note-L21F1" dur="4" oct="2" pname="c" stem.dir="down">
                                        <accid xml:id="accid-L21F1" accid.ges="n" />
                                    </note>
                                    <rest xml:id="rest-L25F1" dur="4" />
                                </layer>
                            </staff>
                            <dynam xml:id="dynam-0000001877487567" staff="1" tstamp="1.000000">f</dynam>
                            <slur xml:id="slur-L13F2-L21F2N1" staff="1" startid="#chord-L13F2" endid="#chord-L21F2" curvedir="above" />
                            <slur xml:id="slur-L22F2-L24F2N1" staff="1" startid="#note-L22F2" endid="#note-L24F2" />
                            <dynam xml:id="dynam-0000001870893603" staff="1" tstamp="4.250000">p</dynam>
                            <slur xml:id="slur-L26F2-L28F2N1" staff="1" startid="#note-L26F2" endid="#note-L28F2" />
                            <slur xml:id="slur-L13F1-L21F1N1" staff="2" startid="#note-L13F1" endid="#note-L21F1" curvedir="below" />
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by lpugin** [comment]
Fixed

![image](https://cloud.githubusercontent.com/assets/689412/25193021/cf730f2e-2535-11e7-8cc5-684dcdba2c37.png)

**Comment by craigsapp** [comment]
Well at least partially fixed, but much better :-) . I think there is another open issue for unattaching the stems from the top staff...

For example, here is the source print for the encoding:

<img width="403" alt="screen shot 2017-04-19 at 11 32 39 am" src="https://cloud.githubusercontent.com/assets/3487289/25195949/f968c888-24f3-11e7-9ef2-85168078113b.png">

**Comment by lpugin** [comment]
For that you need to put the `@staff` on the chord (and with `@stem.dir` for now)

![image](https://cloud.githubusercontent.com/assets/689412/25196433/f3ab6b7e-2540-11e7-9b68-273e7da01308.png)

```xml
<chord xml:id="chord-L13F2" staff="2" dur="2" stem.dir="up">
    <note xml:id="note-L13F2S1"  oct="3" pname="d">
        <accid xml:id="accid-L13F2S1" accid.ges="n" />
    </note>
    <note xml:id="note-L13F2S2" oct="3" pname="f">
        <accid xml:id="accid-L13F2S2" accid.ges="n" />
    </note>
</chord>
<chord xml:id="chord-L21F2" staff="2" dur="16" stem.dir="up">
    <note xml:id="note-L21F2S1" oct="3" pname="c">
        <accid xml:id="accid-L21F2S1" accid.ges="n" />
    </note>
    <note xml:id="note-L21F2S2" oct="3" pname="e">
        <accid xml:id="accid-L21F2S2" accid.ges="n" />
    </note>
</chord>
```

**Comment by craigsapp** [comment]
Thanks!
