### ISSUE TITLE
Strange transient flag on grace notes

### ISSUE THREAD

**Issue by jacekiwaszko1** [rism-ch/verovio#613]
While adding a `<dir>` element to the music, a strange transient flat appears on grace notes:

![grace-flag1](https://user-images.githubusercontent.com/29225574/26873728-29ca3e5a-4b7b-11e7-842c-e778a1e73e2c.png)

![grace-flag2](https://user-images.githubusercontent.com/29225574/26873729-2ba1fc9a-4b7b-11e7-89c1-ae1c159d41a5.png)

The flag only seems to appear on grace notes that are beamed together, and is probably not related to the `<dir>` (I think I saw it with adding pedal markings as well).

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application isodate="2017-06-07T12:16:10" version="0.9.14-dev-abb70fc-dirty">
                    <name>Verovio</name>
                    <p>Transcoded from Humdrum</p>
                </application>
            </appInfo>
        </encodingDesc>
        <workDesc>
            <work>
                <titleStmt>
                    <title />
                </titleStmt>
            </work>
        </workDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-0000000191208818">
                        <staffGrp xml:id="staffgrp-0000001920796184">
                            <staffDef xml:id="staffdef-0000000371259771" n="1" clef.shape="G" clef.line="2" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-0000000754340361">
                        <measure xml:id="measure-L3" n="17">
                            <staff xml:id="staff-L3F1N1" n="1">
                                <layer xml:id="layer-L3F1N1" n="1">
                                    <rest xml:id="rest-L5F1" dur="2" />
                                    <beam xml:id="beam-L6F1-L7F1">
                                        <note xml:id="note-L6F1" dur="32" oct="3" pname="a" grace="unacc" stem.dir="up" accid.ges="n" />
                                        <note xml:id="note-L7F1" dur="32" oct="4" pname="c" grace="unacc" accid="s" />
                                        <note xml:id="note-L8F1" dur="32" oct="4" pname="e" grace="unacc" accid.ges="n" />
                                    </beam>
                                    <note xml:id="note-L9F1" dur="4" oct="4" pname="a" accid.ges="n" />
                                </layer>
                            </staff>
                            <dir xml:id="dir-L5F1" place="above" staff="1" tstamp="1.000000">tsr</dir>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

```
**kern
*clefG2
=17
!LO:TX:a:t=tsr
2r
32A/qLLL
32c#q
32eqJJJ
4a
=19
*-
```

**Comment by rettinghaus** [comment]
Seems to  be fixed now.

**Comment by craigsapp** [comment]
I still see it when typing in text directions:

<img width="727" alt="screen shot 2017-07-11 at 11 42 18 pm" src="https://user-images.githubusercontent.com/3487289/28092183-cc4b50ba-6692-11e7-80f1-cf3bba170051.png">

(although I have not recompiled the javascript version in a few days).

The above is in chrome and below is firefox:

<img width="551" alt="screen shot 2017-07-11 at 11 46 54 pm" src="https://user-images.githubusercontent.com/3487289/28092344-48426e1a-6693-11e7-837f-106dc8923393.png">

Not predictable as to when it happens.

**Comment by lpugin** [comment]
Now fixed e5695b4b1559c81857a66ef3ac88bc4c5cee488f
