### ISSUE TITLE
Tuplets in PAE input have an incorrect numbase

### ISSUE THREAD

**Issue by peterkorgaard** [rism-ch/verovio#829]
I have tested the current development version and have noticed that tuplets is no longer rendered to MIDI. It renders as expected to SVG, but as MIDI it is incorrect. It acts as the tuplets is not existing.

I have created an example to demonstrate this.
http://korgaard.info/tupletNotRenderingToMidiCorrect

I'm really happy with the new version - especially that ties now renders to midi. :-)

**Comment by lpugin** [comment]
There is indeed an issue in the tuplets with PAE.

**Comment by lpugin** [comment]
Fixed

**Comment by rettinghaus** [comment]
Not really fixed, only for triplets. 
The long-pae-tuplet-format gives the duration for the whole tuplet. Wouldn't it be nice if Verovio supported `@dur` and  `@dots` on `<tuplet>` instead of trying to calculate a `@numbase` in PAE importer?
