### ISSUE TITLE
SVG (float formatting) issue with Java on non US locale Ubuntu

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/verovio#996]
Building the Java toolkit fails on Ubuntu 18.10 with swig 3.0.12.
I tried master branch and develop branch.

**Comment by lpugin** [comment]
What it the error?

**Comment by rettinghaus** [comment]
Had to specify the paths to `jni.h` and `jni_md.h`  for g++. I added it to the line in the `build.sh` and now it works. 
But the `output.svg` can't be displayed (although the file looks quite ok).

**Comment by lpugin** [comment]
Can you make a PR with the changes?

**Comment by rettinghaus** [comment]
Will do. 
But the development branch is broken. The svg output with native build only shows a slur, the java output won't work at all (see output files in zip). Any idea?
[importer.zip](https://github.com/rism-ch/verovio/files/2888891/importer.zip)

NB. The java build soutput of the main branch isn't working, too.

**Comment by lpugin** [comment]
> But the development branch is broken.

Can you check with the latest commit? And what command parameter did you use with the native version?

**Comment by rettinghaus** [comment]
Latest commit merged. Just used `./verovio -r ../data ../doc/importer.mei` in tools. Same result.

**Comment by lpugin** [comment]
Should be fixed

**Comment by rettinghaus** [comment]
The SVG output still can't be opened with any viewer I tested.

**Comment by lpugin** [comment]
This is weird. The file `importer-dev-native.svg` in your zip has corrupted dimensions `width="1050,00px" height="322,00px"` and is missing the xml directive. It has a duplicated `@id`, but otherwise it is valid and displays correctly
![image](https://user-images.githubusercontent.com/689412/53249430-56d20e80-36b8-11e9-9e0f-daf109865f46.png)

**Comment by lpugin** [comment]
This is where the dimensions are set
https://github.com/rism-ch/verovio/blob/develop/src/svgdevicecontext.cpp#L83-L93
It is weird that only these values are wrongly formatted.

**Comment by lpugin** [comment]
It all works as expected on Mac OS X (10.14.3), Java 1.8.0_162 and Swig 3.0.12

**Comment by lpugin** [comment]
@rettinghaus any progress on this?

**Comment by rettinghaus** [comment]
No. I tried to play around with the options in in `main.java` without any luck.

**Comment by lpugin** [comment]
Can you confirm that the issue comes from the wrongly formatted dimensions?

**Comment by rettinghaus** [comment]
Yes, the problem is the dimension. It's always the half of the expected value.

**Comment by lpugin** [comment]
I have a hard time following the issue. You sent a file where the dimensions are corrupted (`width="1050,00px"` instead of `width="1050.00px"`) and where the xml directive was missing. You did not comment on this. Would it be possible to elaborate a little bit? What do you mean by "play around with the options"?

**Comment by rettinghaus** [comment]
The problem is obviously the string formatting in java depending on locale. So it formats the float with a comma instead of a dot on my system. 
But adding `Locale.setDefault(Locale.US);` to `main.java` doesn't help. 
Is there a way to solve this within Verovio?

**Comment by lpugin** [comment]
You can try to force the locale in Verovio directly. See https://en.cppreference.com/w/cpp/locale/LC_categories

**Comment by rettinghaus** [comment]
Tried to set it in `main.cpp`, in the `pom.xml`, and in `main.java` in the example folder. 
Didn't work. I really have no clue.

**Comment by lpugin** [comment]
@rettinghaus any progress? (It will be difficult to help without having a German Ubuntu installation, sorry)

**Comment by rettinghaus** [comment]
No, but for now it seems to be ok for my use cases. You may close this here and put it to the back burner list. And maybe a note in the building instructions would be useful?

**Comment by lpugin** [comment]
I added a link to the building instructions
